import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'


export const SmallCard=({image,location,distance})=>{
  return (
    <div className='flex items-center m-2 mt-5 space-x-4 rounded-xl cursor-pointer hover:bg-gray-100 hover:scale-105 transition transform duration-200 ease-out'>
<div className='relative h-16 w-16'>
<Image src={image} layout='fill' className='rounded-lg'  />
</div>

<div>
  <h2>{location}</h2>
  <h3 className='text-gray-500'>{distance}</h3>
</div>

</div>
  )
}

 export function MediumCard({ img,title }) {
  return (
    <div className='cursor-pointer hover:scale-105 transform transition duration-300 ease-out mt-3 ml-3'>
    <div className='relative h-80 w-80'>
    <Image className='rounded-md' layout='fill' src={img}  />
    </div>
    <h3 className='text-2xl mt-3'>{title}</h3>
    </div>
  )
}

export function LargeCard({ img,title,description, buttonText }){
return (
  <div className='relative mt-20'>
  <div className='relative h-96 min-w-[300px]'>
<Image
src={img}
layout='fill'
objectFit='cover'
className='rounded-md'
/>
  </div>
  <div className='absolute top-1/3 left-12'>
    <h3 className='text-4xl mb-3 w-64'>{title}</h3>
    <p>{description}</p>

    <button className='text-sm text-white bg-gray-900 px-4 py-2 mt-3 rounded-[3px] hover:scale-105 transform transition duration-100 ease-out'>{buttonText}</button>
  </div>
  </div>
)
}




export default function Home({exploreDAta, cardsData}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Header />
     <Banner />
     
     <main className='max-w-5xl mx-auto px-8 sm:px-16'>
<section className='pt-6 '>
  <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>

<div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4' >
{exploreDAta?.map((item,i)=>(
<SmallCard 
image={item.img}
distance={item.distance}
location={item.location}
key={i}
/>
))}
</div>
</section>
<section>
  <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>

  <div className='flex space-x-5 overflow-scroll scrollbar-hide p-3 -ml-3'>
  {cardsData?.map((item,i)=>(
    <MediumCard key={i} img={item.img} title={item.title} />
  ))}
  </div>
</section>

<LargeCard img='https://links.papareact.com/4cj' title='The Greatest Outdoors' description='Wishlists curated by Airbnb' buttonText='Get Inspired' />
     </main>
     <Footer />
    </div>
  )
}

export async function getStaticProps(){
  const exploreDAta= await fetch('https://links.papareact.com/pyp').then((res)=>res.json());

const cardsData=await fetch('https://links.papareact.com/zp1').then((res)=>res.json())

   return {
     props:{
       exploreDAta,
       cardsData
     }
   }
  
}
